import type {
    AgentLogEntry,
    AnalyticsSummary,
    Application,
    CVData,
    Job,
    JobAnalysisPayload,
    User,
} from '../types';

export const mockUser: User = {
    id: 'user-1',
    email: 'demo@autoapply.ai',
    cvParsed: true,
    preferences: {
        targetRoles: ['Senior Frontend Developer', 'Frontend Engineer'],
        location: 'Remote',
        salaryExpectation: 80000,
        workType: 'remote',
    },
};

export const mockCV: CVData = {
    name: 'Alex Johnson',
    email: 'alex.johnson@email.com',
    phone: '+1 555 0147',
    summary: 'Frontend-focused software engineer with strong React, TypeScript, Node.js, and cloud delivery experience.',
    skills: ['React', 'TypeScript', 'Node.js', 'Python', 'PostgreSQL', 'AWS', 'Docker', 'GraphQL'],
    languages: ['English'],
    experience: [
        { title: 'Senior Frontend Developer', company: 'TechCorp', duration: '2021 - Present' },
        { title: 'Frontend Developer', company: 'StartupXYZ', duration: '2019 - 2021' },
        { title: 'Junior Developer', company: 'WebAgency', duration: '2017 - 2019' },
    ],
    education: [{ degree: 'B.Sc. Computer Science', school: 'MIT', year: '2017' }],
};

function createAnalysis(jobId: string, fitScore: number, missingSkills: string[] = []): JobAnalysisPayload {
    return {
        job_id: jobId,
        fit_score: fitScore,
        matched_skills: ['React', 'TypeScript', 'Node.js'],
        missing_skills: missingSkills,
        cv_advice: [
            'Move your React architecture work into the top bullet of your latest role.',
            'Quantify impact with one metric tied to the job description.',
        ],
        recommendation: fitScore >= 75 ? 'apply' : 'skip',
        rationale: fitScore >= 75 ? 'Strong overlap across the core frontend stack.' : 'Relevant profile, but some listed requirements are weaker.',
    };
}

export const mockJobs: Job[] = [
    {
        id: 'job-1',
        title: 'Senior Frontend Developer',
        company: 'TechCorp',
        location: 'Remote',
        salaryMin: 80000,
        salaryMax: 120000,
        workType: 'remote',
        source: 'remoteok',
        applyType: 'platform',
        applyUrl: 'https://example.com/jobs/techcorp-senior-frontend',
        description: 'We are looking for a senior frontend developer with React and TypeScript experience to join our growing team.',
        scrapedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        fitScore: 87,
        analysisStatus: 'completed',
        writerStatus: 'completed',
        applicationId: 'app-1',
    },
    {
        id: 'job-2',
        title: 'Full Stack Engineer',
        company: 'InnovateLab',
        location: 'San Francisco, CA',
        salaryMin: 100000,
        salaryMax: 150000,
        workType: 'hybrid',
        source: 'adzuna',
        applyType: 'platform',
        applyUrl: 'https://example.com/jobs/innovatelab-fullstack',
        description: 'Join our team to build next-generation web applications using React, Node.js, and PostgreSQL.',
        scrapedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        fitScore: 72,
        analysisStatus: 'completed',
        writerStatus: 'idle',
        applicationId: 'app-2',
    },
    {
        id: 'job-3',
        title: 'React Developer',
        company: 'CloudScale',
        location: 'Remote',
        salaryMin: 70000,
        salaryMax: 100000,
        workType: 'remote',
        source: 'remoteok',
        applyType: 'email',
        applyUrl: 'https://example.com/jobs/cloudscale-react',
        description: 'Looking for a passionate React developer to help build our cloud infrastructure dashboard.',
        scrapedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        fitScore: 91,
        analysisStatus: 'completed',
        writerStatus: 'completed',
        applicationId: 'app-3',
    },
    {
        id: 'job-4',
        title: 'Frontend Engineer',
        company: 'FinTech Plus',
        location: 'New York, NY',
        salaryMin: 90000,
        salaryMax: 130000,
        workType: 'onsite',
        source: 'adzuna',
        applyType: 'platform',
        applyUrl: 'https://example.com/jobs/fintech-plus-frontend',
        description: 'Build beautiful, performant UIs for our financial trading platform.',
        scrapedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        fitScore: 45,
        analysisStatus: 'completed',
        writerStatus: 'idle',
        applicationId: 'app-4',
    },
    {
        id: 'job-5',
        title: 'UI/UX Developer',
        company: 'DesignHub',
        location: 'London, UK',
        salaryMin: 60000,
        salaryMax: 85000,
        workType: 'hybrid',
        source: 'remoteok',
        applyType: 'email',
        applyUrl: 'https://example.com/jobs/designhub-uiux',
        description: 'We need a creative developer who blends design thinking with frontend development.',
        scrapedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        fitScore: null,
        analysisStatus: 'running',
        writerStatus: 'idle',
        applicationId: 'app-5',
    },
];

export const mockApplications: Application[] = [
    {
        id: 'app-1',
        jobId: 'job-1',
        job: mockJobs[0],
        status: 'applied',
        fitScore: 87,
        analysisPayload: createAnalysis('job-1', 87),
        analysisStatus: 'completed',
        writerStatus: 'completed',
        cvVariantText: 'Senior frontend engineer focused on scalable React and TypeScript product delivery.',
        coverLetterText: 'Dear Hiring Manager,\n\nI am excited to apply for the Senior Frontend Developer role at TechCorp...\n\nBest regards,\nAlex Johnson',
        submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        followUpScheduledAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-2',
        jobId: 'job-2',
        job: mockJobs[1],
        status: 'pending',
        fitScore: 72,
        analysisPayload: createAnalysis('job-2', 72, ['GraphQL']),
        analysisStatus: 'completed',
        writerStatus: 'idle',
        cvVariantText: null,
        coverLetterText: null,
        submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        followUpScheduledAt: null,
    },
    {
        id: 'app-3',
        jobId: 'job-3',
        job: mockJobs[2],
        status: 'interview',
        fitScore: 91,
        analysisPayload: createAnalysis('job-3', 91),
        analysisStatus: 'completed',
        writerStatus: 'completed',
        cvVariantText: 'React specialist with cloud dashboard and cross-functional product delivery experience.',
        coverLetterText: 'Dear CloudScale Hiring Team,\n\nI was thrilled to see the React Developer opening...',
        submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        followUpScheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-4',
        jobId: 'job-4',
        job: mockJobs[3],
        status: 'rejected',
        fitScore: 45,
        analysisPayload: createAnalysis('job-4', 45, ['Fintech domain knowledge', 'Performance profiling']),
        analysisStatus: 'completed',
        writerStatus: 'idle',
        cvVariantText: null,
        coverLetterText: null,
        submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        followUpScheduledAt: null,
    },
    {
        id: 'app-5',
        jobId: 'job-5',
        job: mockJobs[4],
        status: 'pending',
        fitScore: 0,
        analysisPayload: null,
        analysisStatus: 'running',
        writerStatus: 'idle',
        cvVariantText: null,
        coverLetterText: null,
        submittedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
        followUpScheduledAt: null,
    },
];

export const mockAgentLogs: AgentLogEntry[] = [
    { id: 'log-1', agentName: 'scout', action: 'Scanning RemoteOK for "Frontend Developer" positions...', timestamp: new Date(Date.now() - 60000).toISOString() },
    { id: 'log-2', agentName: 'scout', action: 'Found 12 new matching jobs on RemoteOK', timestamp: new Date(Date.now() - 55000).toISOString() },
    { id: 'log-3', agentName: 'analyzer', action: 'Queued manual analysis for Senior Frontend Developer at TechCorp', applicationId: 'app-1', jobId: 'job-1', timestamp: new Date(Date.now() - 40000).toISOString() },
    { id: 'log-4', agentName: 'analyzer', action: 'Fit score calculated: 87/100 for Senior Frontend Developer', applicationId: 'app-1', jobId: 'job-1', timestamp: new Date(Date.now() - 36000).toISOString() },
    { id: 'log-5', agentName: 'writer', action: 'Generated CV summary and cover letter', applicationId: 'app-1', jobId: 'job-1', timestamp: new Date(Date.now() - 32000).toISOString() },
    { id: 'log-6', agentName: 'analyzer', action: 'Fit score calculated: 72/100 for Full Stack Engineer', applicationId: 'app-2', jobId: 'job-2', timestamp: new Date(Date.now() - 18000).toISOString() },
    { id: 'log-7', agentName: 'tracker', action: 'CloudScale interview scheduled for next week', applicationId: 'app-3', jobId: 'job-3', timestamp: new Date(Date.now() - 12000).toISOString() },
    { id: 'log-8', agentName: 'scout', action: 'Found 5 new matching jobs in the last scan', timestamp: new Date(Date.now() - 1000).toISOString() },
];

import type { InterviewPrep } from '../types';

export const mockInterviewPrep = (applicationId: string): InterviewPrep => ({
    id: `prep-${applicationId}`,
    applicationId,
    status: 'completed',
    companyResearch: {
        company_summary: 'CloudScale is a fast-growing B2B SaaS startup providing scalable cloud infrastructure management tools. They recently raised a $25M Series B to expand their developer experience and platform integrations.',
        culture_keywords: ['innovation', 'developer-first', 'remote-friendly', 'fast-paced', 'data-driven'],
        products_or_services: ['CloudScale Dashboard', 'Infra API', 'Serverless Deployments'],
        recent_news: ['CloudScale raises $25M Series B led by Tech Ventures', 'New integration with AWS announced at re:Invent'],
        sources: ['https://example.com/about', 'https://techcrunch.com/cloudscale']
    },
    questions: [
        {
            id: 1,
            category: 'technical',
            question: 'Can you walk me through a time when you had to optimize a slow-rendering React dashboard with large datasets?',
            focus: 'They need someone who can handle complex UI states and performance profiling.'
        },
        {
            id: 2,
            category: 'behavioral',
            question: 'Tell me about a time you disagreed with a product manager or designer on a feature implementation. How did you handle it?',
            focus: 'Cross-functional collaboration in a fast-paced environment.'
        },
        {
            id: 3,
            category: 'role_specific',
            question: 'How would you approach migrating our current React dashboard to use Server Components while maintaining backward compatibility?',
            focus: 'Modern React architecture and migration strategies.'
        }
    ],
    answers: [
        {
            question_id: 1,
            situation: 'At TechCorp, our analytics dashboard was taking over 4 seconds to render when displaying 10,000+ rows of transactional data, leading to customer complaints.',
            task: 'I needed to reduce the time-to-interactive to under 1 second without removing functionality.',
            action: 'I implemented React Window for virtualization to only render visible rows, memoized expensive calculation components with useMemo, and paginated the initial data fetch using React Query.',
            result: 'Load time dropped to 0.8 seconds (an 80% improvement), and customer support tickets regarding dashboard speed fell to zero.',
            talking_points: ['Virtualization (React Window)', 'Memoization (useMemo/useCallback)', 'Data fetching optimization']
        },
        {
            question_id: 2,
            situation: 'At StartupXYZ, a designer proposed a complex animation for a critical user flow that I knew would cause jank on mobile devices.',
            task: 'I needed to communicate the technical constraints while still delivering a great user experience.',
            action: 'I prototyped the proposed animation to show the performance drop, then built a simpler CSS-only alternative. I presented both to the designer, explaining the trade-offs.',
            result: 'The designer appreciated the data-driven approach and agreed to the CSS alternative, which shipped on time and performed smoothly across all devices.',
            talking_points: ['Prototyping', 'Data-driven feedback', 'Compromise']
        },
        {
            question_id: 3,
            situation: 'Based on my experience migrating a legacy application at WebAgency to Next.js...',
            task: 'The goal is a smooth transition without disrupting current users.',
            action: 'I would start by identifying leaf components that don\'t require client-side interactivity and convert them first. I\'d use a feature flag to route a percentage of traffic to the new RSC pages while monitoring error rates.',
            result: 'This incremental approach ensures stability while gradually improving initial page load times and reducing the client-side JavaScript bundle.',
            talking_points: ['Incremental migration', 'Feature flags', 'Leaf components first']
        }
    ],
    errorMessage: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastUpdatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString()
});

export const mockAnalytics: AnalyticsSummary = {
    totalApplications: 4,
    responseRate: 67,
    avgFitScore: 74,
    interviewsScheduled: 1,
    applicationsByStatus: {
        pending: 1,
        applied: 1,
        in_review: 0,
        interview: 1,
        offer: 0,
        rejected: 1,
    },
    applicationsPerDay: [
        { date: '2026-03-18', count: 1 },
        { date: '2026-03-19', count: 0 },
        { date: '2026-03-20', count: 0 },
        { date: '2026-03-21', count: 1 },
        { date: '2026-03-22', count: 0 },
        { date: '2026-03-23', count: 0 },
        { date: '2026-03-24', count: 1 },
        { date: '2026-03-25', count: 0 },
        { date: '2026-03-26', count: 0 },
        { date: '2026-03-27', count: 0 },
        { date: '2026-03-28', count: 1 },
        { date: '2026-03-29', count: 0 },
        { date: '2026-03-30', count: 0 },
        { date: '2026-03-31', count: 0 },
    ],
    fitScoreDistribution: [
        { range: '0-20', count: 0 },
        { range: '21-40', count: 0 },
        { range: '41-60', count: 1 },
        { range: '61-80', count: 1 },
        { range: '81-100', count: 2 },
    ],
};
