import type {
    Job,
    Application,
    AgentLogEntry,
    AnalyticsSummary,
    User,
    CVData,
} from '../types';

// ─── Mock User ─────────────────────────────────────────────────

export const mockUser: User = {
    id: 'user-1',
    email: 'demo@autoapply.ai',
    cvParsed: true,
    preferences: {
        targetRole: 'Senior Frontend Developer',
        location: 'Remote',
        salaryMin: 80000,
        salaryMax: 130000,
        workType: 'remote',
        autoApply: false,
    },
};

// ─── Mock CV ───────────────────────────────────────────────────

export const mockCV: CVData = {
    name: 'Alex Johnson',
    email: 'alex.johnson@email.com',
    skills: ['React', 'TypeScript', 'Node.js', 'Python', 'PostgreSQL', 'AWS', 'Docker', 'GraphQL'],
    experience: [
        { title: 'Senior Frontend Developer', company: 'TechCorp', duration: '2021 – Present' },
        { title: 'Frontend Developer', company: 'StartupXYZ', duration: '2019 – 2021' },
        { title: 'Junior Developer', company: 'WebAgency', duration: '2017 – 2019' },
    ],
    education: [
        { degree: 'B.Sc. Computer Science', school: 'MIT', year: '2017' },
    ],
};

// ─── Mock Jobs ─────────────────────────────────────────────────

export const mockJobs: Job[] = [
    {
        id: 'job-1',
        title: 'Senior Frontend Developer',
        company: 'TechCorp',
        location: 'Remote',
        salaryMin: 80000,
        salaryMax: 120000,
        workType: 'remote',
        source: 'remoteok',
        applyType: 'email',
        description: 'We are looking for a senior frontend developer with React and TypeScript experience to join our growing team.',
        scrapedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        fitScore: 87,
    },
    {
        id: 'job-2',
        title: 'Full Stack Engineer',
        company: 'InnovateLab',
        location: 'San Francisco, CA',
        salaryMin: 100000,
        salaryMax: 150000,
        workType: 'hybrid',
        source: 'adzuna',
        applyType: 'platform',
        description: 'Join our team to build next-generation web applications using React, Node.js, and PostgreSQL.',
        scrapedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        fitScore: 72,
    },
    {
        id: 'job-3',
        title: 'React Developer',
        company: 'CloudScale',
        location: 'Remote',
        salaryMin: 70000,
        salaryMax: 100000,
        workType: 'remote',
        source: 'remoteok',
        applyType: 'email',
        description: 'Looking for a passionate React developer to help build our cloud infrastructure dashboard.',
        scrapedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        fitScore: 91,
    },
    {
        id: 'job-4',
        title: 'Frontend Engineer',
        company: 'FinTech Plus',
        location: 'New York, NY',
        salaryMin: 90000,
        salaryMax: 130000,
        workType: 'onsite',
        source: 'adzuna',
        applyType: 'platform',
        description: 'Build beautiful, performant UIs for our financial trading platform.',
        scrapedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        fitScore: 45,
    },
    {
        id: 'job-5',
        title: 'UI/UX Developer',
        company: 'DesignHub',
        location: 'London, UK',
        salaryMin: 60000,
        salaryMax: 85000,
        workType: 'hybrid',
        source: 'remoteok',
        applyType: 'email',
        description: 'We need a creative developer who blends design thinking with frontend development.',
        scrapedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        fitScore: undefined,
    },
];

// ─── Mock Applications ─────────────────────────────────────────

export const mockApplications: Application[] = [
    {
        id: 'app-1',
        jobId: 'job-1',
        job: mockJobs[0],
        status: 'applied',
        fitScore: 87,
        coverLetterText: 'Dear Hiring Manager,\n\nI am writing to express my strong interest in the Senior Frontend Developer position at TechCorp. With over 5 years of experience in React and TypeScript development, I am confident in my ability to contribute to your team.\n\nMy experience at my current role has equipped me with deep expertise in building scalable, performant web applications. I have led multiple projects from conception to deployment, consistently delivering high-quality code.\n\nI look forward to discussing how my skills align with your team\'s needs.\n\nBest regards,\nAlex Johnson',
        submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        followUpScheduledAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-2',
        jobId: 'job-2',
        job: mockJobs[1],
        status: 'in_review',
        fitScore: 72,
        coverLetterText: 'Dear InnovateLab Team,\n\nI am excited to apply for the Full Stack Engineer position...',
        submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-3',
        jobId: 'job-3',
        job: mockJobs[2],
        status: 'interview',
        fitScore: 91,
        coverLetterText: 'Dear CloudScale Hiring Team,\n\nI was thrilled to see the React Developer opening...',
        submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        followUpScheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-4',
        jobId: 'job-4',
        job: mockJobs[3],
        status: 'rejected',
        fitScore: 45,
        submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-5',
        jobId: 'job-1',
        job: mockJobs[0],
        status: 'applied',
        fitScore: 83,
        submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-6',
        jobId: 'job-2',
        job: mockJobs[1],
        status: 'offer',
        fitScore: 88,
        coverLetterText: 'Dear Hiring Manager,\n\nI am pleased to submit my application...',
        submittedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-7',
        jobId: 'job-3',
        job: mockJobs[2],
        status: 'in_review',
        fitScore: 76,
        submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'app-8',
        jobId: 'job-5',
        job: mockJobs[4],
        status: 'applied',
        fitScore: 65,
        submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        lastUpdatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
];

// ─── Mock Agent Logs ───────────────────────────────────────────

export const mockAgentLogs: AgentLogEntry[] = [
    { id: 'log-1', agentName: 'scout', action: 'Scanning RemoteOK for "Frontend Developer" positions...', timestamp: new Date(Date.now() - 60000).toISOString() },
    { id: 'log-2', agentName: 'scout', action: 'Found 12 new matching jobs on RemoteOK', timestamp: new Date(Date.now() - 55000).toISOString() },
    { id: 'log-3', agentName: 'scout', action: 'Scanning Adzuna for "React Developer" positions...', timestamp: new Date(Date.now() - 50000).toISOString() },
    { id: 'log-4', agentName: 'scout', action: 'Found 8 new matching jobs on Adzuna', timestamp: new Date(Date.now() - 45000).toISOString() },
    { id: 'log-5', agentName: 'analyzer', action: 'Analyzing CV fit for "Senior Frontend Developer" at TechCorp', applicationId: 'app-1', timestamp: new Date(Date.now() - 40000).toISOString() },
    { id: 'log-6', agentName: 'analyzer', action: 'Fit score calculated: 87/100 — Strong match in React, TypeScript', applicationId: 'app-1', timestamp: new Date(Date.now() - 38000).toISOString() },
    { id: 'log-7', agentName: 'writer', action: 'Generating tailored CV variant for TechCorp position', applicationId: 'app-1', timestamp: new Date(Date.now() - 35000).toISOString() },
    { id: 'log-8', agentName: 'writer', action: 'Cover letter generated successfully (487 words)', applicationId: 'app-1', timestamp: new Date(Date.now() - 30000).toISOString() },
    { id: 'log-9', agentName: 'apply', action: 'Submitting application to TechCorp via email', applicationId: 'app-1', timestamp: new Date(Date.now() - 25000).toISOString() },
    { id: 'log-10', agentName: 'apply', action: '✅ Application submitted successfully to TechCorp', applicationId: 'app-1', timestamp: new Date(Date.now() - 23000).toISOString() },
    { id: 'log-11', agentName: 'analyzer', action: 'Analyzing CV fit for "Full Stack Engineer" at InnovateLab', applicationId: 'app-2', timestamp: new Date(Date.now() - 20000).toISOString() },
    { id: 'log-12', agentName: 'analyzer', action: 'Fit score calculated: 72/100 — Good match, missing GraphQL experience', applicationId: 'app-2', timestamp: new Date(Date.now() - 18000).toISOString() },
    { id: 'log-13', agentName: 'tracker', action: 'Checking status of application to InnovateLab...', applicationId: 'app-2', timestamp: new Date(Date.now() - 15000).toISOString() },
    { id: 'log-14', agentName: 'tracker', action: 'Status update: InnovateLab moved to "In Review"', applicationId: 'app-2', timestamp: new Date(Date.now() - 12000).toISOString() },
    { id: 'log-15', agentName: 'writer', action: 'Generating tailored CV variant for CloudScale position', applicationId: 'app-3', timestamp: new Date(Date.now() - 10000).toISOString() },
    { id: 'log-16', agentName: 'apply', action: 'Queuing application for CloudScale — awaiting user approval', applicationId: 'app-3', timestamp: new Date(Date.now() - 8000).toISOString() },
    { id: 'log-17', agentName: 'tracker', action: 'Follow-up email scheduled for TechCorp in 5 days', applicationId: 'app-1', timestamp: new Date(Date.now() - 5000).toISOString() },
    { id: 'log-18', agentName: 'scout', action: 'Scanning RemoteOK for new positions...', timestamp: new Date(Date.now() - 3000).toISOString() },
    { id: 'log-19', agentName: 'tracker', action: '🎉 CloudScale interview scheduled for next week!', applicationId: 'app-3', timestamp: new Date(Date.now() - 2000).toISOString() },
    { id: 'log-20', agentName: 'scout', action: 'Found 5 new matching jobs in the last scan', timestamp: new Date(Date.now() - 1000).toISOString() },
];

// ─── Mock Analytics ────────────────────────────────────────────

export const mockAnalytics: AnalyticsSummary = {
    totalApplications: 47,
    responseRate: 32,
    avgFitScore: 74,
    interviewsScheduled: 5,
    applicationsByStatus: {
        applied: 18,
        in_review: 12,
        interview: 5,
        offer: 3,
        rejected: 9,
    },
    applicationsPerDay: [
        { date: '2026-02-07', count: 3 },
        { date: '2026-02-08', count: 5 },
        { date: '2026-02-09', count: 2 },
        { date: '2026-02-10', count: 4 },
        { date: '2026-02-11', count: 1 },
        { date: '2026-02-12', count: 6 },
        { date: '2026-02-13', count: 3 },
        { date: '2026-02-14', count: 2 },
        { date: '2026-02-15', count: 4 },
        { date: '2026-02-16', count: 5 },
        { date: '2026-02-17', count: 1 },
        { date: '2026-02-18', count: 3 },
        { date: '2026-02-19', count: 2 },
        { date: '2026-02-20', count: 4 },
        { date: '2026-02-21', count: 7 },
        { date: '2026-02-22', count: 3 },
        { date: '2026-02-23', count: 2 },
        { date: '2026-02-24', count: 5 },
        { date: '2026-02-25', count: 4 },
        { date: '2026-02-26', count: 1 },
        { date: '2026-02-27', count: 3 },
        { date: '2026-02-28', count: 6 },
        { date: '2026-03-01', count: 2 },
        { date: '2026-03-02', count: 4 },
        { date: '2026-03-03', count: 3 },
        { date: '2026-03-04', count: 5 },
        { date: '2026-03-05', count: 2 },
        { date: '2026-03-06', count: 4 },
        { date: '2026-03-07', count: 3 },
        { date: '2026-03-08', count: 6 },
    ],
    fitScoreDistribution: [
        { range: '0-20', count: 2 },
        { range: '21-40', count: 5 },
        { range: '41-60', count: 12 },
        { range: '61-80', count: 18 },
        { range: '81-100', count: 10 },
    ],
};
